"""Load the shipped knowledge banks and match them to detected services.

Two JSON files under ``data/`` carry the content, both generated by scripts in
``tools/``:

* ``service_kb.json`` — the per-service enumeration knowledge bank converted
  from the VAPT spreadsheet (one entry per service, keyed by port), plus a
  couple of general methodology pages.
* ``network_kb.json`` — network-layer attack methodology that is not tied to a
  single port (spoofing, IPv6 takeover, VLAN hopping, and so on).

Loading is stdlib ``json`` only; the spreadsheet and its openpyxl dependency
stay on the build side. The banks are read once and cached.
"""

from __future__ import annotations

import json
import os
import re
from functools import lru_cache
from typing import Optional

from .model import Host, Port

_DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")


def _load(name: str) -> dict:
    path = os.path.join(_DATA, name)
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError):
        return {}


def _fill_phase(rows: list[dict]) -> list[dict]:
    """Carry a phase label down the rows it heads.

    The spreadsheet merges the Phase cell vertically, so only the first row of
    each group carries it. Forward-filling restores the grouping the author
    intended.
    """
    out = []
    current = ""
    for row in rows:
        phase = row.get("phase") or current
        current = phase
        out.append(dict(row, phase=phase))
    return out


@lru_cache(maxsize=1)
def service_bank() -> list[dict]:
    """Per-service entries, phase forward-filled, sorted by first port."""
    bank = _load("service_kb.json")
    services = []
    for entry in bank.get("services", []):
        services.append(dict(entry, rows=_fill_phase(entry.get("rows", []))))
    return services


@lru_cache(maxsize=1)
def methodology() -> list[dict]:
    bank = _load("service_kb.json")
    return [dict(e, rows=_fill_phase(e.get("rows", []))) for e in bank.get("methodology", [])]


@lru_cache(maxsize=1)
def network_bank() -> dict:
    return _load("network_kb.json")


@lru_cache(maxsize=1)
def _indexes() -> tuple[dict[int, dict], dict[str, dict]]:
    by_port: dict[int, dict] = {}
    by_alias: dict[str, dict] = {}
    for entry in service_bank():
        for port in entry.get("ports", []):
            by_port.setdefault(int(port), entry)
        for alias in entry.get("aliases", []):
            by_alias.setdefault(alias.lower(), entry)
    return by_port, by_alias


def for_port(port: Port) -> Optional[dict]:
    """The knowledge-bank entry for an open port, matched by number then name."""
    by_port, by_alias = _indexes()
    entry = by_port.get(port.portid)
    if entry is not None:
        return entry
    name = (port.service.name or "").lower()
    if name in by_alias:
        return by_alias[name]
    # nmap prefixes tunnelled services, e.g. "ssl/http".
    if "/" in name:
        return by_alias.get(name.split("/", 1)[1])
    return None


_IP_PLACEHOLDER = re.compile(
    r"<\s*(?:ip|target[\w ]*|host|dns[\w_]*|victim[\w.]*|rhost)\s*>", re.I
)
_PORT_PLACEHOLDER = re.compile(r"<\s*(?:port|rport)\s*>", re.I)


def substitute(text: str, ip: str, port_id: int) -> str:
    """Fill obvious host/port placeholders in a command for a concrete target."""
    text = _IP_PLACEHOLDER.sub(ip, text)
    text = _PORT_PLACEHOLDER.sub(str(port_id), text)
    return text


_CLEARTEXT = {"telnet", "ftp", "http", "pop3", "imap", "snmp", "rlogin", "rsh", "finger"}


def _live(analysis) -> list[Host]:
    return [h for h in analysis.hosts if h.status != "down"]


def _is_ipv6(host: Host) -> bool:
    return any(":" in a for a in (host.addresses or [host.address]) if a)


def relevant_network_topics(analysis) -> tuple[list[tuple[dict, list[str]]], set]:
    """Topics the scan gives evidence for, with a reason each.

    This reports preconditions found in the scan, not confirmed attacks. Layer-2
    and routing attacks (VLAN hopping, HSRP/GLBP/EIGRP, IDS/IPS evasion) are not
    visible to a port scan at all, so they are never surfaced here — they stay in
    the general reference.
    """
    topics = {t["key"]: t for t in network_bank().get("topics", [])}
    reasons: dict[str, list[str]] = {}

    def add(key: str, reason: str) -> None:
        if key in topics:
            reasons.setdefault(key, []).append(reason)

    live = _live(analysis)

    # Open ports/services, and SMB-signing weakness, gathered once.
    open_ports = [(h, p) for h in live for p in h.open_ports if p.service.name != "tcpwrapped"]
    smb_unsigned = {
        w.host for w in getattr(analysis, "weaknesses", []) if w.rule_id == "SMB_SIGNING_DISABLED"
    }

    has_smb = ad_ports = False
    for host, port in open_ports:
        name = (port.service.name or "").lower()
        pid = port.portid
        if pid in (445, 139) or name in ("microsoft-ds", "netbios-ssn"):
            has_smb = True
            if host.address in smb_unsigned:
                add("llmnr-nbtns-mdns-relay",
                    f"SMB signing not required on {host.address}:{pid} — NTLM relay "
                    "precondition met")
        if pid in (88, 389, 636, 3268, 3269) or name in ("kerberos-sec", "ldap", "ldapssl"):
            ad_ports = True
        if name in _CLEARTEXT:
            add("sniffing-arp-spoofing",
                f"cleartext service {name} on {host.address}:{pid} — credentials "
                "exposed to a man-in-the-middle")
        if pid == 1900 or name == "upnp":
            add("ssdp-upnp-evilssdp", f"SSDP/UPnP reachable on {host.address}:{pid}")
        if 7400 <= pid <= 7500 or name.startswith("rtps"):
            add("dds-rtps-impersonation", f"RTPS discovery port {host.address}:{pid} open")
        if pid in (3478, 5349) or name == "stun":
            add("webrtc-dos", f"STUN/TURN on {host.address}:{pid}")
        if pid in (2123, 2152) or name.startswith("gtp"):
            add("telecom-exploitation", f"GTP endpoint on {host.address}:{pid}")

    if has_smb or ad_ports:
        add("llmnr-nbtns-mdns-relay",
            "Windows/Active Directory services present — broadcast name resolution "
            "is likely in use")
        add("dhcpv6-ipv6-takeover",
            "Active Directory environment — mitm6 DHCPv6 takeover is a common vector")

    ipv6_hosts = [h for h in live if _is_ipv6(h)]
    if ipv6_hosts:
        where = ", ".join(h.address for h in ipv6_hosts[:3])
        add("dhcpv6-ipv6-takeover", f"IPv6 address seen ({where}) — DHCPv6 is reachable")
        add("pentesting-ipv6", f"IPv6 hosts present ({where})")

    subnets = {h.address.rsplit(".", 1)[0] for h in live if h.address.count(".") == 3}
    if len([h for h in live if h.open_ports]) >= 2 and len(subnets) <= 2:
        add("sniffing-arp-spoofing",
            "multiple live hosts share the broadcast domain — LAN man-in-the-middle "
            "is in reach")

    ordered = sorted(
        (topics[k] for k in reasons),
        key=lambda t: [x["key"] for x in topics.values()].index(t["key"]),
    )
    out = [(t, sorted(set(reasons[t["key"]]))) for t in ordered]
    return out, set(reasons)


# nmap scripts worth adding for a service on a follow-up scan.
_FOLLOWUP_SCRIPTS = {
    "http": ["http-enum", "http-title", "http-headers", "http-methods"],
    "https": ["http-enum", "http-title", "ssl-enum-ciphers", "ssl-cert"],
    "ssh": ["ssh2-enum-algos", "ssh-hostkey"],
    "ftp": ["ftp-anon", "ftp-syst"],
    "smtp": ["smtp-commands", "smtp-open-relay"],
    "domain": ["dns-recursion", "dns-nsid"],
    "microsoft-ds": ["smb-protocols", "smb-security-mode", "smb-os-discovery", "smb-enum-shares"],
    "netbios-ssn": ["smb-protocols", "smb-security-mode", "nbstat"],
    "ldap": ["ldap-rootdse"],
    "snmp": ["snmp-info"],
    "mysql": ["mysql-info"],
    "ms-sql-s": ["ms-sql-info", "ms-sql-ntlm-info"],
    "redis": ["redis-info"],
    "mongodb": ["mongodb-info", "mongodb-databases"],
    "rdp": ["rdp-enum-encryption", "rdp-ntlm-info"],
    "ms-wbt-server": ["rdp-enum-encryption", "rdp-ntlm-info"],
    "vnc": ["vnc-info"],
    "nfs": ["nfs-showmount", "nfs-ls"],
    "rpcbind": ["rpcinfo"],
}


def followup_scan(analysis) -> list[dict]:
    """A targeted next nmap run derived from the services already found.

    Returns ``{label, command}`` entries: one script-driven TCP scan per host
    carrying the scripts that match its open services, plus a UDP suggestion.
    """
    out: list[dict] = []
    for host in _live(analysis):
        ports = sorted({p.portid for p in host.open_ports if p.service.name != "tcpwrapped"})
        if not ports:
            continue
        scripts: list[str] = []
        for port in host.open_ports:
            for script in _FOLLOWUP_SCRIPTS.get((port.service.name or "").lower(), []):
                if script not in scripts:
                    scripts.append(script)
        plist = ",".join(str(p) for p in ports)
        if scripts:
            cmd = (f"nmap -sV -sC -p {plist} --script \"{','.join(scripts)}\" "
                   f"-oA {host.address}-deep {host.address}")
        else:
            cmd = f"nmap -sV -sC -p {plist} -oA {host.address}-deep {host.address}"
        out.append({"label": f"Deep scan of {host.address}", "command": cmd})
    if out:
        out.append({
            "label": "UDP top ports (services a TCP scan misses)",
            "command": "nmap -sU --top-ports 100 -oA udp-scan "
            + " ".join(sorted({h.address for h in _live(analysis) if h.open_ports})),
        })
    return out


def detected(hosts: list[Host]) -> list[tuple[dict, list[str]]]:
    """Knowledge-bank entries for the services actually seen, with where.

    Returns ``(entry, ["10.0.0.5:22", ...])`` pairs, ordered by the entry's
    first port, each service once however many hosts expose it.
    """
    hits: dict[str, list[str]] = {}
    entries: dict[str, dict] = {}
    for host in hosts:
        if host.status == "down":
            continue
        for port in host.open_ports:
            if port.service.name == "tcpwrapped":
                continue
            entry = for_port(port)
            if entry is None:
                continue
            key = entry["key"]
            entries[key] = entry
            hits.setdefault(key, []).append(f"{host.address}:{port.portid}")

    ordered = sorted(
        entries.values(), key=lambda e: (e["ports"][0] if e.get("ports") else 99999, e["name"])
    )
    return [(entry, hits[entry["key"]]) for entry in ordered]
